### ISSUE TITLE
Impossible to install the app

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/bibliogram_ynh#1]
**Describe the bug**
Impossible to install the app

**Versions**
- Hardware: computer
- YunoHost version: 4.0.4
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | ...
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no

**To Reproduce**
*Steps to reproduce the behavior.*
  1. Create a new domain *bibliogram.myserver.fr*
  2. install certificates using CLI `sudo yunohost domain cert-install bibliogram.myserver.fr --no-checks`
  3. Install Bibliogram in this domain (at the root) using the web interface

**Expected behavior**
App is installed

**Logs**
https://paste.yunohost.org/abomutosuq.log

**Comment by ericgaspar** [comment]
It looks like your GPG key for Yarn has expired. Can you try this command to reimport it?

`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

**Comment by supermamie** [comment]
It worked.
Can this be added in the install doc somewhere ?
