### ISSUE TITLE
 Install fails: Crystal dependency repository is not available

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/bibliogram_ynh#17]
Same as https://github.com/YunoHost-Apps/invidious_ynh/issues/24

**Comment by lapineige** [comment]
It works again… so the service was unavailable.

**Comment by lapineige** [comment]
Hum… not quite solved:

>  WARNING - W: GPG error: https://dl.bintray.com/crystal/deb all Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61

**Comment by ericgaspar** [comment]
I think this as nothing to do with Bibliogram and that you will get the same warning with another app using apt-get
Can you try this to reimport the key:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61`
