### ISSUE TITLE
RSS / Atom feeds with wrong url

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/bibliogram_ynh#2]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Versions**
- Hardware: computer
- YunoHost version: 4.0.4
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | ...
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no

**To Reproduce**
  1. Go in Bibliogram
  2. Search for a user
  3. Click on RSS or Atom
  4. Import the feed in your favorite feed reader or open it via a text editor

**Expected behavior**
Links inside of the feed should point to Bibliogram

**Actual behaviour**
The links point to the internal url of Bibliogram : http://127.0.0.1:10407 (instead of https://bibliogram.myserver.fr )
So images can not be displayed and link point to nowhere.

**Comment by ericgaspar** [comment]
Thanks for reporting this. I will push a PR to fix it.
In the meantime you can try to change the config file `/var/www/bibliogram/config.js` and replace `http://127.0.0.1:10407` by your domain `https://bibliogram.myserver.fr`

**Comment by supermamie** [comment]
After changing this and restaring the service, it does work :smiley:
