### ISSUE TITLE
Apparently the Bibliogram project was shut down by Facebook

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/bibliogram_ynh#27]
Yesterday I got contacted by this guy https://austinhuang.me/ who seem to also have some forks of Bibliogram, and he told me that Bibliogram announced on their Matrix channel #bibliogram:matrix.org :

```
I have received an email from Facebook's data policy team.

Bibliogram will immediately have all contact links and commit metadata removed. Please save a copy of the repository as it currently stands - it will be force-pushed.
```

Indeed the sources for Bibliogram that you link to are private or not working.

I cannot confirm this is indeed true but something seems to be going on with Bibliogram.

**Comment by alexAubin** [comment]
Apparently https://git.sr.ht/~cadence/bibliogram is up again ?

**Comment by ericgaspar** [comment]
the project repo is no longer public... You can't git clone -> `fatal: unable to access 'https://git.sr.ht/~cadence/bibliogram/': SSL certificate problem: Invalid certificate chain`

**Comment by mustermann2021** [comment]
> the project repo is no longer public... You can't git clone -> `fatal: unable to access 'https://git.sr.ht/~cadence/bibliogram/': SSL certificate problem: Invalid certificate chain`

It seems like it's possible again. Works with my server...
