### ISSUE TITLE
Returning 503 and 504 errors

### ISSUE THREAD

**Issue by LukeOssevoort** [YunoHost-Apps/bibliogram_ynh#31]
### Describe the bug

New install of Bibliogram is only giving 504 or 503 errors

### Context

- Hardware: RPi4
- YunoHost version: 4.3.6.2
- I have access to my server: SSH and Webadmin
- Using, or trying to install package version/branch: 1.0.0~ynh11

### Logs

[Bibliogram Logs](https://paste.yunohost.org/azehisemih)

**Comment by narFnarF** [comment]
I have the same issue, on a Raspberry Pi 3.
Fresh install of Yunohost, up to date. Installed Bibliogram and I get 504 errors.

(I can open a new ticket if you prefer)
