### ISSUE TITLE
Instagram changes broke my instance

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/bibliogram_ynh#9]
**Describe the bug**
My instance is unusable, any username give me the message "Unexpected end of JSON input". According the upstream app developer, it's because some instagram changes and i have to "update and type npm install". I actually can't do anything but wait until you update the package.

**Versions**
- Hardware: Desktop PC
- YunoHost version: 4.0.8.2
- I have access to my server: full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: master

**To Reproduce**
*Steps to reproduce the behavior.*
   1. Go to Page main app
   2. Type some username

**Expected behavior**
The actual instagram page

**Comment by ericgaspar** [comment]
@stemy2 I have installed a fresh version and the app works as expected.

can you try to:
- In ssh, go to `/var/www/bibliogram/` and `npm install` (you may need to restart the bibliogram service -> webadmin -> services)
- Reinstall the app

**Comment by stemy2** [comment]
The fix worked fine !
